// This is currently generated by the plugin
import { awesomeFunction } from "../some-module/some-feature";

// An option to prefer this import over the other would be nice.
// import { awesomeFunction } from "../some-module";

// Also another option to add the 'index' suffix
// would be needed for systemjs users.
// import { awesomeFunction } from "../some-module/index";

console.log(awesomeFunction());